import { ThemeTokens } from '../types';

// ─────────────────────────────────────────────────────────────────────────────
// 8 Built-in Themes
// ─────────────────────────────────────────────────────────────────────────────

export const BUILT_IN_THEMES: ThemeTokens[] = [
  {
    id: 'amoled',
    name: 'AMOLED',
    isBuiltIn: true,
    colors: {
      background: '#000000',
      surface: '#0d0d0d',
      surfaceAlt: '#1a1a1a',
      border: '#2a2a2a',
      text: '#ffffff',
      textMuted: '#a0a0a0',
      textSubtle: '#606060',
      accent: '#6366f1',
      accentMuted: '#312e81',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      onAccent: '#ffffff',
    },
    fontFamily: 'Inter',
    fontScale: 1.0,
    cornerRadius: 12,
    blurIntensity: 0,
    widgetOpacity: 0.9,
    animationSpeed: 1.0,
    accentColor: '#6366f1',
  },
  {
    id: 'material',
    name: 'Material',
    isBuiltIn: true,
    colors: {
      background: '#1c1b1f',
      surface: '#2b2930',
      surfaceAlt: '#3b3940',
      border: '#4a4750',
      text: '#e6e1e5',
      textMuted: '#cac4d0',
      textSubtle: '#7f7589',
      accent: '#d0bcff',
      accentMuted: '#4a3f70',
      success: '#aff4c6',
      warning: '#ffd8a1',
      error: '#ffb4ab',
      onAccent: '#381e72',
    },
    fontFamily: 'Roboto',
    fontScale: 1.0,
    cornerRadius: 16,
    blurIntensity: 0,
    widgetOpacity: 0.95,
    animationSpeed: 1.0,
    accentColor: '#d0bcff',
  },
  {
    id: 'glass',
    name: 'Glass',
    isBuiltIn: true,
    colors: {
      background: '#0f172a',
      surface: 'rgba(255,255,255,0.08)',
      surfaceAlt: 'rgba(255,255,255,0.12)',
      border: 'rgba(255,255,255,0.15)',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      textSubtle: '#475569',
      accent: '#38bdf8',
      accentMuted: '#0c4a6e',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      onAccent: '#0f172a',
    },
    fontFamily: 'Inter',
    fontScale: 1.0,
    cornerRadius: 20,
    blurIntensity: 16,
    widgetOpacity: 0.75,
    animationSpeed: 0.9,
    accentColor: '#38bdf8',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    isBuiltIn: true,
    colors: {
      background: '#fafafa',
      surface: '#ffffff',
      surfaceAlt: '#f4f4f5',
      border: '#e4e4e7',
      text: '#18181b',
      textMuted: '#71717a',
      textSubtle: '#a1a1aa',
      accent: '#18181b',
      accentMuted: '#e4e4e7',
      success: '#16a34a',
      warning: '#d97706',
      error: '#dc2626',
      onAccent: '#ffffff',
    },
    fontFamily: 'Inter',
    fontScale: 1.0,
    cornerRadius: 8,
    blurIntensity: 0,
    widgetOpacity: 1.0,
    animationSpeed: 0.8,
    accentColor: '#18181b',
  },
  {
    id: 'retro',
    name: 'Retro',
    isBuiltIn: true,
    colors: {
      background: '#1a1209',
      surface: '#2d1f0e',
      surfaceAlt: '#3d2b14',
      border: '#6b4c22',
      text: '#f5dfa0',
      textMuted: '#c9a96e',
      textSubtle: '#8b7045',
      accent: '#f5a623',
      accentMuted: '#7a4f10',
      success: '#9dc057',
      warning: '#f5a623',
      error: '#e05a4e',
      onAccent: '#1a1209',
    },
    fontFamily: 'SpaceMono',
    fontScale: 1.0,
    cornerRadius: 4,
    blurIntensity: 0,
    widgetOpacity: 0.92,
    animationSpeed: 1.2,
    accentColor: '#f5a623',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    isBuiltIn: true,
    colors: {
      background: '#0d1117',
      surface: '#161b22',
      surfaceAlt: '#21262d',
      border: '#30363d',
      text: '#00ff41',
      textMuted: '#00b32c',
      textSubtle: '#006416',
      accent: '#00ff41',
      accentMuted: '#003d10',
      success: '#00ff41',
      warning: '#ffff00',
      error: '#ff0000',
      onAccent: '#0d1117',
    },
    fontFamily: 'SpaceMono',
    fontScale: 1.0,
    cornerRadius: 2,
    blurIntensity: 0,
    widgetOpacity: 0.95,
    animationSpeed: 0.7,
    accentColor: '#00ff41',
  },
  {
    id: 'neon',
    name: 'Neon',
    isBuiltIn: true,
    colors: {
      background: '#050010',
      surface: '#0f0025',
      surfaceAlt: '#1a0040',
      border: '#4d00b3',
      text: '#f0e6ff',
      textMuted: '#c084fc',
      textSubtle: '#7e22ce',
      accent: '#e879f9',
      accentMuted: '#701a75',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f43f5e',
      onAccent: '#050010',
    },
    fontFamily: 'Outfit',
    fontScale: 1.0,
    cornerRadius: 14,
    blurIntensity: 8,
    widgetOpacity: 0.88,
    animationSpeed: 0.9,
    accentColor: '#e879f9',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    isBuiltIn: true,
    colors: {
      background: '#0a0014',
      surface: '#100020',
      surfaceAlt: '#1a0030',
      border: '#ff0090',
      text: '#00ffff',
      textMuted: '#00cccc',
      textSubtle: '#008080',
      accent: '#ff0090',
      accentMuted: '#6b003c',
      success: '#00ff9f',
      warning: '#ffe600',
      error: '#ff2b4e',
      onAccent: '#0a0014',
    },
    fontFamily: 'Outfit',
    fontScale: 1.0,
    cornerRadius: 0,
    blurIntensity: 4,
    widgetOpacity: 0.9,
    animationSpeed: 0.8,
    accentColor: '#ff0090',
  },
];

export const DEFAULT_THEME_ID = 'amoled';

export const getThemeById = (id: string): ThemeTokens =>
  BUILT_IN_THEMES.find((t) => t.id === id) ?? BUILT_IN_THEMES[0];
